import random

FONT_COLOUR = (225, 225, 225)
WIDTH = 800
HEIGHT = 600
CENTER_X = WIDTH / 2
CENTER_Y = HEIGHT / 2
CENTER = (CENTER_X, CENTER_Y)
FINAL_SPEED = 6
START_SPEED = 10
COLOURS = ['green', 'blue']